web:
  build: .
  links:
   - db
  command: bash -c "bower update --allow-root && node server"
  ports:
   - "3000:3000"
  volumes:
   - /c/Users/kskalvar/git/mean:/home/mean
db:
  image: mongo
  ports: 
   - "27017:27017"
